// Static coupon data
export const coupons = [
  // Food & Dining
  {
    id: 1,
    name: 'Uber Eats',
    discount: '50% off',
    code: 'SAVE50',
    category: 'Food',
    expiry: '2026-12-31',
    link: 'https://ubereats.com',
    description: 'Get 50% off your first order',
  },
  {
    id: 2,
    name: 'DoorDash',
    discount: '$15 off',
    code: 'DASH15',
    category: 'Food',
    expiry: '2026-12-31',
    link: 'https://doordash.com',
    description: '$15 off orders over $25',
  },
  {
    id: 3,
    name: 'Grubhub',
    discount: '30% off',
    code: 'GRUB30',
    category: 'Food',
    expiry: '2026-11-30',
    link: 'https://grubhub.com',
    description: '30% off with code',
  },
  {
    id: 4,
    name: 'HelloFresh',
    discount: '60% off',
    code: 'HELLO60',
    category: 'Food',
    expiry: '2026-10-31',
    link: 'https://hellofresh.com',
    description: 'First box 60% off + free shipping',
  },
  {
    id: 5,
    name: 'EveryPlate',
    discount: '$10 off',
    code: 'PLATE10',
    category: 'Food',
    expiry: '2026-11-15',
    link: 'https://everyplate.com',
    description: 'Save on meal kits',
  },
  {
    id: 6,
    name: 'Freshly',
    discount: '40% off',
    code: 'FRESH40',
    category: 'Food',
    expiry: '2026-09-30',
    link: 'https://freshly.com',
    description: 'Fresh meals delivered',
  },

  // Shopping
  {
    id: 7,
    name: 'Amazon Prime',
    discount: '1 month free',
    code: 'PRIME30',
    category: 'Shopping',
    expiry: '2026-12-31',
    link: 'https://amazon.com',
    description: 'Free trial for new members',
  },
  {
    id: 8,
    name: 'Shein',
    discount: '$20 off',
    code: 'SHEIN20',
    category: 'Shopping',
    expiry: '2026-10-31',
    link: 'https://shein.com',
    description: '$20 off orders over $50',
  },
  {
    id: 9,
    name: 'AliExpress',
    discount: '25% off',
    code: 'ALI25',
    category: 'Shopping',
    expiry: '2026-11-30',
    link: 'https://aliexpress.com',
    description: '25% off new customer orders',
  },
  {
    id: 10,
    name: 'Target',
    discount: '20% off',
    code: 'TARGET20',
    category: 'Shopping',
    expiry: '2026-10-15',
    link: 'https://target.com',
    description: 'Circle member exclusive',
  },
  {
    id: 11,
    name: 'Walmart+',
    discount: '3 months free',
    code: 'WALMART90',
    category: 'Shopping',
    expiry: '2026-09-30',
    link: 'https://walmart.com',
    description: 'Free shipping & delivery',
  },
  {
    id: 12,
    name: 'Etsy',
    discount: '$10 off',
    code: 'ETSY10',
    category: 'Shopping',
    expiry: '2026-11-30',
    link: 'https://etsy.com',
    description: 'On purchases over $30',
  },

  // Travel
  {
    id: 13,
    name: 'Booking.com',
    discount: '35% off',
    code: 'BOOK35',
    category: 'Travel',
    expiry: '2026-12-31',
    link: 'https://booking.com',
    description: 'Hotels & resorts',
  },
  {
    id: 14,
    name: 'Airbnb',
    discount: '$75 off',
    code: 'AIRBNB75',
    category: 'Travel',
    expiry: '2026-12-31',
    link: 'https://airbnb.com',
    description: 'First booking credit',
  },
  {
    id: 15,
    name: 'Expedia',
    discount: '40% off',
    code: 'EXPEDIA40',
    category: 'Travel',
    expiry: '2026-11-30',
    link: 'https://expedia.com',
    description: 'Flights & hotels',
  },
  {
    id: 16,
    name: 'Kayak',
    discount: 'Price match',
    code: 'KAYAK',
    category: 'Travel',
    expiry: '2026-10-31',
    link: 'https://kayak.com',
    description: 'Find best deals',
  },
  {
    id: 17,
    name: 'Hotels.com',
    discount: 'Free night',
    code: 'HOTEL10',
    category: 'Travel',
    expiry: '2026-11-15',
    link: 'https://hotels.com',
    description: 'Every 10 nights free',
  },
  {
    id: 18,
    name: 'Spirit Airlines',
    discount: '$30 off',
    code: 'SPIRIT30',
    category: 'Travel',
    expiry: '2026-10-31',
    link: 'https://spirit.com',
    description: 'Flight bookings',
  },

  // Tech & Software
  {
    id: 19,
    name: 'Adobe Creative Cloud',
    discount: '45% off',
    code: 'ADOBE45',
    category: 'Tech',
    expiry: '2026-12-31',
    link: 'https://adobe.com',
    description: 'Annual subscription',
  },
  {
    id: 20,
    name: 'Microsoft 365',
    discount: '25% off',
    code: 'MS365',
    category: 'Tech',
    expiry: '2026-11-30',
    link: 'https://microsoft.com',
    description: 'Office & cloud storage',
  },
  {
    id: 21,
    name: 'Canva Pro',
    discount: '50% off',
    code: 'CANVA50',
    category: 'Tech',
    expiry: '2026-10-31',
    link: 'https://canva.com',
    description: 'First year only',
  },
  {
    id: 22,
    name: 'Figma',
    discount: '20% off annual',
    code: 'FIGMA20',
    category: 'Tech',
    expiry: '2026-11-30',
    link: 'https://figma.com',
    description: 'Professional plan',
  },
  {
    id: 23,
    name: 'Notion',
    discount: 'Free upgrade',
    code: 'NOTION',
    category: 'Tech',
    expiry: '2026-12-31',
    link: 'https://notion.so',
    description: 'First month free',
  },
  {
    id: 24,
    name: 'Dropbox',
    discount: '1TB free',
    code: 'DROP1TB',
    category: 'Tech',
    expiry: '2026-10-15',
    link: 'https://dropbox.com',
    description: 'Cloud storage bonus',
  },

  // Fashion
  {
    id: 25,
    name: 'ASOS',
    discount: '30% off',
    code: 'ASOS30',
    category: 'Fashion',
    expiry: '2026-11-30',
    link: 'https://asos.com',
    description: 'Clothing & accessories',
  },
  {
    id: 26,
    name: 'H&M',
    discount: '25% off',
    code: 'HM25',
    category: 'Fashion',
    expiry: '2026-10-31',
    link: 'https://hm.com',
    description: 'New season collection',
  },
  {
    id: 27,
    name: 'Zara',
    discount: '20% off',
    code: 'ZARA20',
    category: 'Fashion',
    expiry: '2026-11-15',
    link: 'https://zara.com',
    description: 'Sale items extra',
  },
  {
    id: 28,
    name: 'Forever 21',
    discount: '40% off',
    code: 'F2140',
    category: 'Fashion',
    expiry: '2026-12-31',
    link: 'https://forever21.com',
    description: 'Everything in store',
  },
  {
    id: 29,
    name: 'Nike',
    discount: '30% off',
    code: 'NIKE30',
    category: 'Fashion',
    expiry: '2026-10-31',
    link: 'https://nike.com',
    description: 'Shoes & apparel',
  },
  {
    id: 30,
    name: 'Adidas',
    discount: '35% off',
    code: 'ADIDAS35',
    category: 'Fashion',
    expiry: '2026-11-30',
    link: 'https://adidas.com',
    description: 'Apparel & footwear',
  },

  // Additional coupons for variety
  {
    id: 31,
    name: 'Spotify Premium',
    discount: '3 months free',
    code: 'SPOT3M',
    category: 'Tech',
    expiry: '2026-12-31',
    link: 'https://spotify.com',
    description: 'Ad-free music',
  },
  {
    id: 32,
    name: 'Netflix',
    discount: '1 month free',
    code: 'NETFLIX',
    category: 'Tech',
    expiry: '2026-11-30',
    link: 'https://netflix.com',
    description: 'Standard plan',
  },
  {
    id: 33,
    name: 'Starbucks',
    discount: '$10 off',
    code: 'STAR10',
    category: 'Food',
    expiry: '2026-10-31',
    link: 'https://starbucks.com',
    description: 'On $25+ gift card',
  },
  {
    id: 34,
    name: 'McDonald\'s',
    discount: 'Free item',
    code: 'MCDONALD',
    category: 'Food',
    expiry: '2026-12-31',
    link: 'https://mcdonalds.com',
    description: 'With $20 purchase',
  },
  {
    id: 35,
    name: 'Lululemon',
    discount: '25% off',
    code: 'LULU25',
    category: 'Fashion',
    expiry: '2026-11-30',
    link: 'https://lululemon.com',
    description: 'Activewear & yoga',
  },
  {
    id: 36,
    name: 'Uniqlo',
    discount: '30% off',
    code: 'UNIQLO30',
    category: 'Fashion',
    expiry: '2026-10-31',
    link: 'https://uniqlo.com',
    description: 'Basic essentials',
  },
  {
    id: 37,
    name: 'eBay',
    discount: '$25 off',
    code: 'EBAY25',
    category: 'Shopping',
    expiry: '2026-11-15',
    link: 'https://ebay.com',
    description: 'On first purchase',
  },
  {
    id: 38,
    name: 'Costco',
    discount: '$60 card',
    code: 'COSTCO60',
    category: 'Shopping',
    expiry: '2026-09-30',
    link: 'https://costco.com',
    description: 'Membership bonus',
  },
  {
    id: 39,
    name: 'TikTok Shop',
    discount: '$15 off',
    code: 'TIKTOK15',
    category: 'Shopping',
    expiry: '2026-11-30',
    link: 'https://tiktok.com/shop',
    description: 'Orders over $30',
  },
  {
    id: 40,
    name: 'Pinterest+',
    discount: 'Free month',
    code: 'PIN1M',
    category: 'Tech',
    expiry: '2026-10-31',
    link: 'https://pinterest.com',
    description: 'Ad-free browsing',
  },
];

export default function handler(req, res) {
  res.status(200).json(coupons);
}
